<?php

use App\Game;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;

class GamesSeederTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Schema::disableForeignKeyConstraints();
        Game::truncate();

        Game::insert([
            [ 
                'game_title' => 'Dragon Fight',
                'game_company' => 'PS4',
                'game_photo1' => 'zuNqrJ2ZQ8rXHydAYjrDIUWvYe6SMHaYkH9VTG7T.jpg',
                'game_photo2' => 'BNRGqwGQvENlv3C2JbvM5WbHxU7GhaTUDbqsbVoD.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
            [ 
                'game_title' => 'Street Fighter',
                'game_company' => 'PS4',
                'game_photo1' => 'mPy7eg6tzEWgFz3z924D7XYJg22lWP5NJqyVnxiW.jpg',
                'game_photo2' => 'l1SDrKDWY6MwTC18lFWgOypqHoNmR6zqtXQ3a3Mp.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
            [ 
                'game_title' => 'Justice League',
                'game_company' => 'PS4',
                'game_photo1' => 'g96LvGVgmCdSQZPWrqeMMzZR4MAME238I4vZx6k4.jpg',
                'game_photo2' => '4MfHACj3UWWYVEPCK2AlShiRuF8zg1K1WNBnBLiO.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
            [ 
                'game_title' => 'The Mob Rules',
                'game_company' => 'GOOGLEPLAY',
                'game_photo1' => 'w5zh49h0FN9LD3I3z5XyntU2UlFLE41gjdJPK9Ii.jpg',
                'game_photo2' => 'HzBkCoxkoVqa4G3dCBRb7idSb1VWNrS83C5WKnaP.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
            [ 
                'game_title' => 'Hell Gate',
                'game_company' => 'Steam',
                'game_photo1' => 'Ij5ArQn0GPfVKglBwVSbqgDmkI8laWZICVCbmPeO.jpg',
                'game_photo2' => 'Gee29LYLdjN0GhsVL6ysOtonXUCQpOEGbuGi5gZI.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
            [ 
                'game_title' => 'Mafia Mystrey',
                'game_company' => 'XBOX ONE',
                'game_photo1' => 'bYezPAWih92AP7XHps2VRGHa2xXtSxeyW8DWtwXj.jpg',
                'game_photo2' => 'JVM4OARDJwq2uSXNCiNBXIYptKIXYRKuWNfK2lIv.jpg',
                'game_subtitle' => 'Lorem ipsum is simply free text used by copytyping refreshing.',
                'game_description1' => "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tincidunt mi ut mauris varius, vitae lobortis erat ullamcorper. Pellentesque vel dolor non nisi fringilla scelerisque in non ante.",
                'game_button' => 'Download Game',
                'game_url' => '#',
                'game_launchdate' => Carbon::now()->format('Y-m-d'),
                'game_note1' => 'Reader will be distracted by the readable content of a page when looking at its layout',
                'game_note2' => 'Various versions have evolved over the years, sometimes by accident',
                'game_note3' => 'The majority have suffered alteration in some form',
                'game_feature_title1' => 'horor & Adventure',
                'game_feature_subtitle1' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title2' => 'Multi Players',
                'game_feature_subtitle2' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title3' => 'Real Graphic Heroes',
                'game_feature_subtitle3' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'game_feature_title4' => 'Smooth Controlling',
                'game_feature_subtitle4' => 'Lorem ipsum is simply are many variations of pass of majority.',
                'created_at' => now(),
            ],
        ]);

        Schema::enableForeignKeyConstraints();
    }
}
